using FluentMigrator;

namespace GoExpressTMS.Migrations.DefaultDB
{

    [Migration(20190328230110)]
    public class DefaultDB_20190328230110_Veiculos : Migration
    {
        public override void Up()
        {
            this.CreateTableWithId32("VeiculoFabricante", "VeiculoFabricanteId", s => s
                           .WithColumn("Nome").AsString(80).NotNullable());

            this.CreateTableWithId32("VeiculoModelo", "VeiculoModeloId", s => s
                            .WithColumn("VeiculoFabricanteId").AsInt32().NotNullable().ForeignKey("FK_VeiculoModelo_VeiculoFabricanteId", "VeiculoFabricante", "VeiculoFabricanteId")
                            .WithColumn("Nome").AsString(80).NotNullable());

            Execute.Sql("SET IDENTITY_INSERT [dbo].[VeiculoFabricante] ON");
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "1", Nome = "CHEVROLET" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "2", Nome = "VOLKSWAGEN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "3", Nome = "FIAT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "4", Nome = "MERCEDES-BENZ" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "5", Nome = "CITROEN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "6", Nome = "CHANA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "7", Nome = "HONDA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "8", Nome = "SUBARU" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "10", Nome = "FERRARI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "11", Nome = "BUGATTI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "12", Nome = "LAMBORGHINI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "13", Nome = "FORD" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "14", Nome = "HYUNDAI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "15", Nome = "JAC" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "16", Nome = "KIA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "17", Nome = "GURGEL" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "18", Nome = "DODGE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "19", Nome = "CHRYSLER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "20", Nome = "BENTLEY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "21", Nome = "SSANGYONG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "22", Nome = "PEUGEOT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "23", Nome = "TOYOTA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "24", Nome = "RENAULT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "25", Nome = "ACURA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "26", Nome = "ADAMO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "27", Nome = "AGRALE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "28", Nome = "ALFA ROMEO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "29", Nome = "AMERICAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "31", Nome = "ASTON MARTIN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "32", Nome = "AUDI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "34", Nome = "BEACH" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "35", Nome = "BIANCO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "36", Nome = "BMW" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "37", Nome = "BORGWARD" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "38", Nome = "BRILLIANCE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "41", Nome = "BUICK" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "42", Nome = "CBT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "43", Nome = "NISSAN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "44", Nome = "CHAMONIX" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "46", Nome = "CHEDA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "47", Nome = "CHERY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "48", Nome = "CORD" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "49", Nome = "COYOTE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "50", Nome = "CROSS LANDER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "51", Nome = "DAEWOO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "52", Nome = "DAIHATSU" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "53", Nome = "VOLVO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "54", Nome = "DE SOTO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "55", Nome = "DETOMAZO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "56", Nome = "DELOREAN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "57", Nome = "DKW-VEMAG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "59", Nome = "SUZUKI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "60", Nome = "EAGLE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "61", Nome = "EFFA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "63", Nome = "ENGESA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "64", Nome = "ENVEMO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "65", Nome = "FARUS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "66", Nome = "FERCAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "68", Nome = "FNM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "69", Nome = "PONTIAC" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "70", Nome = "PORSCHE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "72", Nome = "GEO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "74", Nome = "GRANCAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "75", Nome = "GREAT WALL" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "76", Nome = "HAFEI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "78", Nome = "HOFSTETTER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "79", Nome = "HUDSON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "80", Nome = "HUMMER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "82", Nome = "INFINITI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "83", Nome = "INTERNATIONAL" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "84", Nome = "ISUZU" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "85", Nome = "IVECO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "86", Nome = "JAGUAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "87", Nome = "JEEP" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "88", Nome = "JINBEI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "89", Nome = "JPX" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "90", Nome = "KAISER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "91", Nome = "KOENIGSEGG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "92", Nome = "LAUTOMOBILE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "93", Nome = "LAUTOCRAFT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "94", Nome = "LADA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "95", Nome = "LANCIA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "96", Nome = "LAND ROVER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "97", Nome = "LEXUS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "98", Nome = "LIFAN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "99", Nome = "LINCOLN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "100", Nome = "LOBINI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "101", Nome = "LOTUS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "102", Nome = "MAHINDRA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "104", Nome = "MASERATI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "106", Nome = "MATRA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "107", Nome = "MAYBACH" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "108", Nome = "MAZDA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "109", Nome = "MENON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "110", Nome = "MERCURY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "111", Nome = "MITSUBISHI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "112", Nome = "MG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "113", Nome = "MINI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "114", Nome = "MIURA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "115", Nome = "MORRIS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "116", Nome = "MP LAFER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "117", Nome = "MPLM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "118", Nome = "NEWTRACK" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "119", Nome = "NISSIN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "120", Nome = "OLDSMOBILE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "121", Nome = "PAG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "122", Nome = "PAGANI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "123", Nome = "PLYMOUTH" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "124", Nome = "PUMA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "125", Nome = "RENO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "126", Nome = "REVA-I" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "127", Nome = "ROLLS-ROYCE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "129", Nome = "ROMI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "130", Nome = "SEAT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "131", Nome = "UTILITARIOS AGRICOLAS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "132", Nome = "SHINERAY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "133", Nome = "KASINSKI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "135", Nome = "YAMAHA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "136", Nome = "GARINNI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "137", Nome = "SAAB" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "139", Nome = "SHORT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "140", Nome = "SUNDOWN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "141", Nome = "SIMCA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "142", Nome = "SMART" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "143", Nome = "SPYKER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "144", Nome = "STANDARD" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "145", Nome = "STUDEBAKER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "146", Nome = "TAC" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "147", Nome = "TANGER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "148", Nome = "TRIUMPH" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "149", Nome = "TROLLER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "150", Nome = "UNIMOG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "154", Nome = "WIESMANN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "155", Nome = "CADILLAC" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "156", Nome = "AM GEN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "157", Nome = "BUGGY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "158", Nome = "WILLYS OVERLAND" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "161", Nome = "KASEA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "162", Nome = "SATURN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "163", Nome = "SWELL MINI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "164", Nome = "TRAILER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "167", Nome = "RANDON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "170", Nome = "KAWASAKI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "171", Nome = "POLARIS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "175", Nome = "SKODA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "176", Nome = "ADLY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "177", Nome = "AMAZONAS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "178", Nome = "APRILIA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "179", Nome = "ATALA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "180", Nome = "BAJAJ" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "181", Nome = "BENELLI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "182", Nome = "BETA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "183", Nome = "BIMOTA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "184", Nome = "BRANDY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "185", Nome = "BRAVA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "186", Nome = "BRP" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "187", Nome = "BUELL" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "188", Nome = "BUENO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "190", Nome = "CAGIVA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "191", Nome = "MOBILETE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "192", Nome = "DAELIM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "193", Nome = "DAFRA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "194", Nome = "DAYANG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "195", Nome = "DAYUN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "196", Nome = "DERBI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "197", Nome = "DUCATI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "198", Nome = "EMME" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "200", Nome = "FYM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "201", Nome = "GAS GAS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "202", Nome = "GREEN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "203", Nome = "HAOBAO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "204", Nome = "HARLEY-DAVIDSON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "205", Nome = "HARTFORD" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "206", Nome = "HERO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "207", Nome = "HUSABERG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "208", Nome = "HUSQVARNA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "209", Nome = "IROS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "210", Nome = "JIAPENG VOLCANO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "211", Nome = "JOHNNYPAG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "212", Nome = "JONNY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "213", Nome = "KAHENA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "214", Nome = "KIMCO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "215", Nome = "LAQUILA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "216", Nome = "LANDUM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "217", Nome = "LAVRALE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "218", Nome = "LERIVO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "219", Nome = "LON-V" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "220", Nome = "TRICICLO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "221", Nome = "MALAGUTI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "222", Nome = "MIZA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "223", Nome = "MOTO GUZZI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "224", Nome = "MRX" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "225", Nome = "MV AUGUSTA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "226", Nome = "MVK" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "227", Nome = "ORCA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "228", Nome = "PEGASSI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "229", Nome = "PIAGGIO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "230", Nome = "REGAL RAPTOR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "231", Nome = "SANYANG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "232", Nome = "SIAMOTO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "233", Nome = "TARGOS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "234", Nome = "TRAXX" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "235", Nome = "VENTO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "236", Nome = "WUYANG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "239", Nome = "KARMANN GHIA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "242", Nome = "SCANIA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "245", Nome = "GARRA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "246", Nome = "X MOTOS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "248", Nome = "TRICKER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "253", Nome = "LAMBRETA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "254", Nome = "KART" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "258", Nome = "HANOMAG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "261", Nome = "OUTROS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "263", Nome = "ONIBUS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "265", Nome = "HILLMAN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "266", Nome = "UTILITARIOS PESADOS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "269", Nome = "SCOOTER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "270", Nome = "MOTOR-HOME" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "274", Nome = "MAN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "275", Nome = "NAVISTAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "277", Nome = "SINOTRUK" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "281", Nome = "ZONGSHEN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "282", Nome = "BIRELLI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "284", Nome = "SCHIFFER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "285", Nome = "GUERRA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "288", Nome = "HRG" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "292", Nome = "MICHIGAN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "294", Nome = "WALK MACHINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "295", Nome = "GAIOLA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "297", Nome = "FBM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "299", Nome = "ARIEL" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "338", Nome = "TATA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "340", Nome = "DUCAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "341", Nome = "DITALLY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "342", Nome = "MARVA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "343", Nome = "WOLVER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "344", Nome = "KTM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "345", Nome = "RELY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "346", Nome = "MCLAREN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "347", Nome = "LEOPARD" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "348", Nome = "JAWA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "349", Nome = "BULL" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "351", Nome = "ECOMARINER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "352", Nome = "VENTURA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "353", Nome = "EVINRUDE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "354", Nome = "FIBRAFORT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "355", Nome = "SCHAEFER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "356", Nome = "CARBRASMAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "357", Nome = "SEA-DOO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "358", Nome = "CAN-AM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "359", Nome = "ACELLERA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "360", Nome = "INTERMARINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "361", Nome = "MAGNA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "362", Nome = "AZIMUT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "363", Nome = "CIMITARRA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "364", Nome = "FERRETTI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "365", Nome = "BENETEAU" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "366", Nome = "MONTE CARLO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "367", Nome = "LAGOON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "368", Nome = "FISHING" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "369", Nome = "REAL POWER BOATS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "370", Nome = "MAGNUM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "371", Nome = "AGUZ" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "372", Nome = "MILLENIUM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "373", Nome = "ALTERNATIVA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "374", Nome = "BAYLINER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "375", Nome = "AQUA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "376", Nome = "MOONEN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "377", Nome = "AQUATERRA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "378", Nome = "ARMADA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "379", Nome = "ARTHMARINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "380", Nome = "AXTOR MARINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "381", Nome = "AVALON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "382", Nome = "BAIA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "383", Nome = "BAJA MARINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "384", Nome = "BENETTI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "385", Nome = "BILGIN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "386", Nome = "BMYD" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "387", Nome = "BRASBOATS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "388", Nome = "BRAVA YACHTS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "389", Nome = "BRAZILIAN BOAT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "390", Nome = "CANTIERI DI PISA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "391", Nome = "CAPRICE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "392", Nome = "CENTURY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "393", Nome = "CHRIS CRAFT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "394", Nome = "COLUNNA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "395", Nome = "CORAL" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "396", Nome = "CRANCHI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "397", Nome = "CROWNLINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "398", Nome = "LUNA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "400", Nome = "MERCURY MARINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "401", Nome = "MAGIS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "402", Nome = "TOP BOATS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "403", Nome = "DIAMAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "404", Nome = "COBRA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "405", Nome = "ARBOAT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "406", Nome = "ALBATROZ" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "407", Nome = "B3" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "408", Nome = "BATE VENTO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "409", Nome = "BERTRAM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "410", Nome = "BRAMADOR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "411", Nome = "BRUDDEN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "412", Nome = "CARABELLI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "413", Nome = "DONZI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "414", Nome = "DELTA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "415", Nome = "LEVEFORT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "416", Nome = "NAUTIQUE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "417", Nome = "EDGEWATER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "418", Nome = "FORMULA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "419", Nome = "HARRIS FLOTEBOTE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "420", Nome = "MASTERCRAFT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "421", Nome = "DOLPHIN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "422", Nome = "DREAMBOATS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "423", Nome = "ESQUIMAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "424", Nome = "EUROBOATS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "425", Nome = "EVOLUTION" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "426", Nome = "EVOLVE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "427", Nome = "FAIRLINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "429", Nome = "MIDNIGHT EXPRESS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "430", Nome = "STATEMENT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "431", Nome = "MTI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "432", Nome = "LUND" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "433", Nome = "ALUMACRAFT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "434", Nome = "LOWE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "435", Nome = "FLASH" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "436", Nome = "FLEXBOAT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "437", Nome = "FLORIDA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "438", Nome = "YANMAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "439", Nome = "FLYBOAT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "440", Nome = "FORCE ONE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "441", Nome = "FOUNTAINE PAJOT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "442", Nome = "FOUR WINNS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "443", Nome = "FS YACHTS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "444", Nome = "FUTURA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "445", Nome = "GAMPER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "446", Nome = "GENESIS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "447", Nome = "GIANETTI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "448", Nome = "HD MARINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "449", Nome = "HOLOS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "450", Nome = "BELASSI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "451", Nome = "IMPERIO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "452", Nome = "INACE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "453", Nome = "INTECH" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "454", Nome = "JEANNEAU" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "455", Nome = "PRESTIGE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "456", Nome = "PALMER JOHNSON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "457", Nome = "KALMAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "458", Nome = "LENZI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "459", Nome = "LANCER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "460", Nome = "LAZZARA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "461", Nome = "TRIUMPH BOATS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "462", Nome = "LOTHAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "463", Nome = "MAESTRALE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "464", Nome = "MALIBU" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "465", Nome = "MARES" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "466", Nome = "MARINER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "467", Nome = "MASTERBOAT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "468", Nome = "MAXIMA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "469", Nome = "MCP YACHTS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "470", Nome = "METALGLASS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "471", Nome = "MINASFORTE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "472", Nome = "MJ YACHTS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "473", Nome = "MOCHI CRAFT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "474", Nome = "MONTEREY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "475", Nome = "MOOMBA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "476", Nome = "MWM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "477", Nome = "NAUTIFLEX" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "478", Nome = "PAPA E PALAZZINI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "479", Nome = "PERI YACHTS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "480", Nome = "PERSHING" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "481", Nome = "PHANTOM" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "482", Nome = "PHOENIX" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "483", Nome = "VICTORY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "484", Nome = "INDIAN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "485", Nome = "POLARIS BOATS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "486", Nome = "PRINCESS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "487", Nome = "PROMAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "488", Nome = "PSARI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "489", Nome = "RANGER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "490", Nome = "RECON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "491", Nome = "REGAL" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "492", Nome = "RIOSTAR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "493", Nome = "RIVA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "494", Nome = "RIVAL" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "495", Nome = "ROYAL MARINER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "496", Nome = "RUNNER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "497", Nome = "SAGA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "498", Nome = "SAIL MASTER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "499", Nome = "SAPPHIRE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "500", Nome = "SEA CREST" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "501", Nome = "SEA RAY" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "502", Nome = "SEA HAWK" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "503", Nome = "SEGUE YACHTS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "504", Nome = "SESSA MARINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "505", Nome = "SILVERTON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "506", Nome = "SKIPPER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "507", Nome = "STERLING" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "508", Nome = "STRIDER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "509", Nome = "SUNFLASH" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "510", Nome = "SUNLINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "511", Nome = "SUNSEEKER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "512", Nome = "SUPERBOATS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "513", Nome = "SUPRA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "514", Nome = "TECNOBOATS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "515", Nome = "TECHNOMARINE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "516", Nome = "TEMPEST" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "517", Nome = "TOHATSU" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "518", Nome = "TRITON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "519", Nome = "VEGA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "520", Nome = "VICTORY YACHTS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "521", Nome = "WALGLASS" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "522", Nome = "WELLCRAFT" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "523", Nome = "YACXO" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "524", Nome = "ZEFIR" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "525", Nome = "ZODIAC" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "526", Nome = "ZONDA" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "527", Nome = "FLIPPER" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "528", Nome = "GALEON" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "529", Nome = "HEESEN" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "530", Nome = "KRAUSE" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "531", Nome = "SUNREEF" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "532", Nome = "BRAVAX" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "533", Nome = "GARELLI" });
            Insert.IntoTable("VeiculoFabricante").Row(new { VeiculoFabricanteId = "534", Nome = "GEELY" });
            Execute.Sql("SET IDENTITY_INSERT [dbo].[VeiculoFabricante] OFF");

            Execute.Sql("SET IDENTITY_INSERT [dbo].[VeiculoModelo] ON");
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "320", VeiculoFabricanteId = "14", Nome = "HR" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "734", VeiculoFabricanteId = "4", Nome = "1113" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "735", VeiculoFabricanteId = "4", Nome = "1214" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "736", VeiculoFabricanteId = "4", Nome = "1318" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "738", VeiculoFabricanteId = "4", Nome = "1519" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "739", VeiculoFabricanteId = "4", Nome = "1614" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "740", VeiculoFabricanteId = "4", Nome = "1620" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "746", VeiculoFabricanteId = "27", Nome = "7000D" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "748", VeiculoFabricanteId = "4", Nome = "709" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "749", VeiculoFabricanteId = "4", Nome = "710" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "750", VeiculoFabricanteId = "4", Nome = "912" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "753", VeiculoFabricanteId = "4", Nome = "2000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1452", VeiculoFabricanteId = "164", Nome = "TRAILER" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1453", VeiculoFabricanteId = "13", Nome = "F-12000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1461", VeiculoFabricanteId = "2", Nome = "MASCARELLO" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1462", VeiculoFabricanteId = "2", Nome = "GRANMICRO" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1482", VeiculoFabricanteId = "263", Nome = "ONIBUS" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1483", VeiculoFabricanteId = "266", Nome = "GUINDASTE" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1511", VeiculoFabricanteId = "266", Nome = "EMPILHADEIRA" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1519", VeiculoFabricanteId = "242", Nome = "112" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1521", VeiculoFabricanteId = "27", Nome = "10000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1522", VeiculoFabricanteId = "27", Nome = "13000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1523", VeiculoFabricanteId = "27", Nome = "14000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1524", VeiculoFabricanteId = "27", Nome = "1600" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1525", VeiculoFabricanteId = "27", Nome = "1800" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1526", VeiculoFabricanteId = "27", Nome = "4500" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1527", VeiculoFabricanteId = "27", Nome = "5000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1528", VeiculoFabricanteId = "27", Nome = "6000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1529", VeiculoFabricanteId = "27", Nome = "7000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1530", VeiculoFabricanteId = "27", Nome = "7500" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1531", VeiculoFabricanteId = "27", Nome = "8000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1532", VeiculoFabricanteId = "27", Nome = "8500" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1533", VeiculoFabricanteId = "27", Nome = "8700" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1534", VeiculoFabricanteId = "27", Nome = "9200" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1536", VeiculoFabricanteId = "1", Nome = "D-12000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1537", VeiculoFabricanteId = "1", Nome = "D-13000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1538", VeiculoFabricanteId = "1", Nome = "D-14000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1539", VeiculoFabricanteId = "1", Nome = "19000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1540", VeiculoFabricanteId = "1", Nome = "21000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1541", VeiculoFabricanteId = "1", Nome = "22000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1542", VeiculoFabricanteId = "1", Nome = "D-6000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1543", VeiculoFabricanteId = "1", Nome = "C-60" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1544", VeiculoFabricanteId = "1", Nome = "D-40" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1545", VeiculoFabricanteId = "1", Nome = "D-60" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1546", VeiculoFabricanteId = "1", Nome = "D-70" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1549", VeiculoFabricanteId = "61", Nome = "JBC" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1550", VeiculoFabricanteId = "61", Nome = "N601" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1551", VeiculoFabricanteId = "61", Nome = "N900" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1552", VeiculoFabricanteId = "3", Nome = "190" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1626", VeiculoFabricanteId = "13", Nome = "CARGO" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1627", VeiculoFabricanteId = "13", Nome = "F-11000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1629", VeiculoFabricanteId = "13", Nome = "F-13000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1630", VeiculoFabricanteId = "13", Nome = "F-14000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1631", VeiculoFabricanteId = "13", Nome = "F-16000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1632", VeiculoFabricanteId = "13", Nome = "F-19000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1633", VeiculoFabricanteId = "13", Nome = "F-2000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1634", VeiculoFabricanteId = "13", Nome = "F-21000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1635", VeiculoFabricanteId = "13", Nome = "F-22000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1636", VeiculoFabricanteId = "13", Nome = "F-350" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1637", VeiculoFabricanteId = "13", Nome = "F-4" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1638", VeiculoFabricanteId = "13", Nome = "F-4000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1639", VeiculoFabricanteId = "13", Nome = "F-7000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1640", VeiculoFabricanteId = "13", Nome = "F-MAXX" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1641", VeiculoFabricanteId = "1", Nome = "12-170" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1642", VeiculoFabricanteId = "1", Nome = "14-190" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1643", VeiculoFabricanteId = "1", Nome = "15-190" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1644", VeiculoFabricanteId = "1", Nome = "16-220" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1645", VeiculoFabricanteId = "1", Nome = "3500" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1646", VeiculoFabricanteId = "1", Nome = "32994" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1647", VeiculoFabricanteId = "1", Nome = "6-100" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1648", VeiculoFabricanteId = "1", Nome = "6-150" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1649", VeiculoFabricanteId = "1", Nome = "7-110" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1650", VeiculoFabricanteId = "14", Nome = "HD78" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1651", VeiculoFabricanteId = "85", Nome = "CITYCLASS" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1652", VeiculoFabricanteId = "85", Nome = "CURSOR" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1653", VeiculoFabricanteId = "85", Nome = "DAILY" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1661", VeiculoFabricanteId = "85", Nome = "EUROCARGO" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1664", VeiculoFabricanteId = "85", Nome = "EUROTECH" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1665", VeiculoFabricanteId = "85", Nome = "EUROTRAKKER" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1666", VeiculoFabricanteId = "85", Nome = "POWERSTAR" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1667", VeiculoFabricanteId = "85", Nome = "STRALIS" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1670", VeiculoFabricanteId = "85", Nome = "TECTOR" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1671", VeiculoFabricanteId = "85", Nome = "TRAKKER" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1672", VeiculoFabricanteId = "85", Nome = "VERTIS" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1673", VeiculoFabricanteId = "274", Nome = "TGX" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1679", VeiculoFabricanteId = "4", Nome = "1114" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1681", VeiculoFabricanteId = "4", Nome = "1215" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1682", VeiculoFabricanteId = "4", Nome = "1218" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1684", VeiculoFabricanteId = "4", Nome = "1414" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1686", VeiculoFabricanteId = "4", Nome = "1420" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1687", VeiculoFabricanteId = "4", Nome = "1714" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1689", VeiculoFabricanteId = "4", Nome = "1720" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1690", VeiculoFabricanteId = "4", Nome = "1721" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1691", VeiculoFabricanteId = "4", Nome = "1723" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1693", VeiculoFabricanteId = "4", Nome = "1938" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1694", VeiculoFabricanteId = "4", Nome = "1944-S" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1695", VeiculoFabricanteId = "4", Nome = "2038" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1696", VeiculoFabricanteId = "4", Nome = "2418" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1697", VeiculoFabricanteId = "4", Nome = "2423" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1699", VeiculoFabricanteId = "4", Nome = "2638" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1700", VeiculoFabricanteId = "4", Nome = "2726" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1701", VeiculoFabricanteId = "4", Nome = "608" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1702", VeiculoFabricanteId = "4", Nome = "708" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1705", VeiculoFabricanteId = "4", Nome = "712" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1707", VeiculoFabricanteId = "4", Nome = "914" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1709", VeiculoFabricanteId = "4", Nome = "ACCELO" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1710", VeiculoFabricanteId = "4", Nome = "ACTROS" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1711", VeiculoFabricanteId = "4", Nome = "ATEGO" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1712", VeiculoFabricanteId = "4", Nome = "ATILIS" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1713", VeiculoFabricanteId = "4", Nome = "ATRON" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1714", VeiculoFabricanteId = "4", Nome = "AXOR" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1717", VeiculoFabricanteId = "4", Nome = "L-1117" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1718", VeiculoFabricanteId = "4", Nome = "L-1118" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1721", VeiculoFabricanteId = "4", Nome = "L-1313" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1722", VeiculoFabricanteId = "4", Nome = "L-1314" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1724", VeiculoFabricanteId = "4", Nome = "L-1317" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1726", VeiculoFabricanteId = "4", Nome = "L-1319" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1730", VeiculoFabricanteId = "4", Nome = "L-1514" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1732", VeiculoFabricanteId = "4", Nome = "L-1517" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1735", VeiculoFabricanteId = "4", Nome = "1520" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1744", VeiculoFabricanteId = "4", Nome = "L-2014" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1745", VeiculoFabricanteId = "4", Nome = "L-2017" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1746", VeiculoFabricanteId = "4", Nome = "L-2213" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1747", VeiculoFabricanteId = "4", Nome = "L-2214" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1748", VeiculoFabricanteId = "4", Nome = "L-2215" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1749", VeiculoFabricanteId = "4", Nome = "L-2216" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1750", VeiculoFabricanteId = "4", Nome = "L-2217" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1752", VeiculoFabricanteId = "4", Nome = "L-2220" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1753", VeiculoFabricanteId = "4", Nome = "L-2225" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1754", VeiculoFabricanteId = "4", Nome = "L-2314" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1755", VeiculoFabricanteId = "4", Nome = "L-2318" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1756", VeiculoFabricanteId = "4", Nome = "L-2325" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1757", VeiculoFabricanteId = "4", Nome = "2635" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1771", VeiculoFabricanteId = "4", Nome = "LS-1632" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1780", VeiculoFabricanteId = "4", Nome = "LS-1941" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1783", VeiculoFabricanteId = "275", Nome = "DURASTAR" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1784", VeiculoFabricanteId = "275", Nome = "INTERNATIONAL" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1792", VeiculoFabricanteId = "124", Nome = "7900" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1793", VeiculoFabricanteId = "124", Nome = "9000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1794", VeiculoFabricanteId = "124", Nome = "914" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1795", VeiculoFabricanteId = "137", Nome = "R-112" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1796", VeiculoFabricanteId = "137", Nome = "R-142" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1797", VeiculoFabricanteId = "137", Nome = "T-112" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1798", VeiculoFabricanteId = "137", Nome = "T-142" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1800", VeiculoFabricanteId = "242", Nome = "380" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1801", VeiculoFabricanteId = "242", Nome = "400" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1802", VeiculoFabricanteId = "242", Nome = "420" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1803", VeiculoFabricanteId = "242", Nome = "440" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1804", VeiculoFabricanteId = "242", Nome = "470" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1805", VeiculoFabricanteId = "242", Nome = "480" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1806", VeiculoFabricanteId = "242", Nome = "111" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1807", VeiculoFabricanteId = "242", Nome = "141" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1808", VeiculoFabricanteId = "242", Nome = "114" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1810", VeiculoFabricanteId = "242", Nome = "230" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1811", VeiculoFabricanteId = "242", Nome = "P-250" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1812", VeiculoFabricanteId = "242", Nome = "P-270" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1813", VeiculoFabricanteId = "242", Nome = "P-310" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1814", VeiculoFabricanteId = "242", Nome = "P-340" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1817", VeiculoFabricanteId = "242", Nome = "93" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1818", VeiculoFabricanteId = "242", Nome = "94" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1822", VeiculoFabricanteId = "242", Nome = "143" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1823", VeiculoFabricanteId = "242", Nome = "164" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1830", VeiculoFabricanteId = "242", Nome = "R-500" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1831", VeiculoFabricanteId = "242", Nome = "R-560" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1832", VeiculoFabricanteId = "242", Nome = "R-580" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1833", VeiculoFabricanteId = "242", Nome = "R-620" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1839", VeiculoFabricanteId = "277", Nome = "HOWO" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1840", VeiculoFabricanteId = "2", Nome = "11-130" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1841", VeiculoFabricanteId = "2", Nome = "11-140" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1842", VeiculoFabricanteId = "2", Nome = "12-170" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1843", VeiculoFabricanteId = "2", Nome = "12-180" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1844", VeiculoFabricanteId = "2", Nome = "13-130" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1845", VeiculoFabricanteId = "2", Nome = "13-150" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1846", VeiculoFabricanteId = "2", Nome = "13-170" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1849", VeiculoFabricanteId = "2", Nome = "14-140" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1850", VeiculoFabricanteId = "2", Nome = "14-150" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1851", VeiculoFabricanteId = "2", Nome = "14-170" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1852", VeiculoFabricanteId = "2", Nome = "14-180" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1853", VeiculoFabricanteId = "2", Nome = "14-200" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1854", VeiculoFabricanteId = "2", Nome = "14-210" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1855", VeiculoFabricanteId = "2", Nome = "14-220" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1856", VeiculoFabricanteId = "2", Nome = "15-170" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1859", VeiculoFabricanteId = "2", Nome = "16-170" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1860", VeiculoFabricanteId = "2", Nome = "16-200" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1861", VeiculoFabricanteId = "2", Nome = "16-210" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1862", VeiculoFabricanteId = "2", Nome = "16-220" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1863", VeiculoFabricanteId = "2", Nome = "16-300" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1864", VeiculoFabricanteId = "2", Nome = "17-180" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1866", VeiculoFabricanteId = "2", Nome = "17-210" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1867", VeiculoFabricanteId = "2", Nome = "17-220" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1869", VeiculoFabricanteId = "2", Nome = "17-280" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1870", VeiculoFabricanteId = "2", Nome = "17-300" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1871", VeiculoFabricanteId = "2", Nome = "17-310" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1873", VeiculoFabricanteId = "2", Nome = "17-330" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1874", VeiculoFabricanteId = "2", Nome = "18-310" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1876", VeiculoFabricanteId = "2", Nome = "19-330" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1878", VeiculoFabricanteId = "2", Nome = "19-390" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1879", VeiculoFabricanteId = "2", Nome = "22-140" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1880", VeiculoFabricanteId = "2", Nome = "22-160" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1881", VeiculoFabricanteId = "2", Nome = "22-210" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1882", VeiculoFabricanteId = "2", Nome = "23-210" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1883", VeiculoFabricanteId = "2", Nome = "23-220" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1884", VeiculoFabricanteId = "2", Nome = "23-250" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1885", VeiculoFabricanteId = "2", Nome = "23-310" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1886", VeiculoFabricanteId = "2", Nome = "24-220" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1888", VeiculoFabricanteId = "2", Nome = "24-280" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1890", VeiculoFabricanteId = "2", Nome = "24-330" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1893", VeiculoFabricanteId = "2", Nome = "25-390" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1894", VeiculoFabricanteId = "2", Nome = "26-220" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1896", VeiculoFabricanteId = "2", Nome = "26-280" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1897", VeiculoFabricanteId = "2", Nome = "26-300" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1898", VeiculoFabricanteId = "2", Nome = "26-310" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1900", VeiculoFabricanteId = "2", Nome = "26-390" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1902", VeiculoFabricanteId = "2", Nome = "31-280" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1903", VeiculoFabricanteId = "2", Nome = "31-310" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1905", VeiculoFabricanteId = "2", Nome = "31-330" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1907", VeiculoFabricanteId = "2", Nome = "31-390" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1908", VeiculoFabricanteId = "2", Nome = "35-300" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1909", VeiculoFabricanteId = "2", Nome = "40-300" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1912", VeiculoFabricanteId = "2", Nome = "29373" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1913", VeiculoFabricanteId = "2", Nome = "33025" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1914", VeiculoFabricanteId = "2", Nome = "7-100" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1915", VeiculoFabricanteId = "2", Nome = "7-110" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1916", VeiculoFabricanteId = "2", Nome = "33055" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1917", VeiculoFabricanteId = "2", Nome = "8-100" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1918", VeiculoFabricanteId = "2", Nome = "8-120" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1919", VeiculoFabricanteId = "2", Nome = "8-140" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1924", VeiculoFabricanteId = "2", Nome = "L-80" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1925", VeiculoFabricanteId = "53", Nome = "FH SERIES" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1926", VeiculoFabricanteId = "53", Nome = "FH GLOBETROTTER SERIES" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1938", VeiculoFabricanteId = "53", Nome = "FM SERIES" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1944", VeiculoFabricanteId = "53", Nome = "FMX SERIES" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1951", VeiculoFabricanteId = "53", Nome = "N SERIES" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1953", VeiculoFabricanteId = "53", Nome = "NH SERIES" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1954", VeiculoFabricanteId = "53", Nome = "NL SERIES" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1956", VeiculoFabricanteId = "53", Nome = "VM SERIES" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1994", VeiculoFabricanteId = "2", Nome = "11-160" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1995", VeiculoFabricanteId = "2", Nome = "12-140" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1996", VeiculoFabricanteId = "2", Nome = "17-230" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1997", VeiculoFabricanteId = "2", Nome = "24-230" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1998", VeiculoFabricanteId = "2", Nome = "28-440" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "1999", VeiculoFabricanteId = "2", Nome = "29-440" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2000", VeiculoFabricanteId = "2", Nome = "31-440" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2001", VeiculoFabricanteId = "2", Nome = "33-440" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2002", VeiculoFabricanteId = "2", Nome = "16-180" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2003", VeiculoFabricanteId = "2", Nome = "17-240" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2004", VeiculoFabricanteId = "2", Nome = "17-260" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2005", VeiculoFabricanteId = "2", Nome = "18-320" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2006", VeiculoFabricanteId = "2", Nome = "18-330" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2007", VeiculoFabricanteId = "2", Nome = "15-210" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2016", VeiculoFabricanteId = "4", Nome = "1516" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2018", VeiculoFabricanteId = "4", Nome = "1935" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2019", VeiculoFabricanteId = "4", Nome = "2555" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2020", VeiculoFabricanteId = "4", Nome = "0-400" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2021", VeiculoFabricanteId = "284", Nome = "BI-TREM" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2022", VeiculoFabricanteId = "285", Nome = "BITREM" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2023", VeiculoFabricanteId = "4", Nome = "1513" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2024", VeiculoFabricanteId = "1", Nome = "D-1200" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2025", VeiculoFabricanteId = "13", Nome = "F-3500" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2026", VeiculoFabricanteId = "13", Nome = "F-600" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2027", VeiculoFabricanteId = "4", Nome = "2219" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2028", VeiculoFabricanteId = "4", Nome = "1313" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2029", VeiculoFabricanteId = "85", Nome = "35-10" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2033", VeiculoFabricanteId = "1", Nome = "MARTA-ROCHA" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2038", VeiculoFabricanteId = "4", Nome = "1929" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2042", VeiculoFabricanteId = "242", Nome = "124" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2051", VeiculoFabricanteId = "4", Nome = "1618" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2052", VeiculoFabricanteId = "4", Nome = "1934" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2053", VeiculoFabricanteId = "4", Nome = "1924" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2054", VeiculoFabricanteId = "4", Nome = "1634" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2060", VeiculoFabricanteId = "13", Nome = "F-400" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2062", VeiculoFabricanteId = "270", Nome = "MOTOR-HOME" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2064", VeiculoFabricanteId = "292", Nome = "PA CARREGADEIRA" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2085", VeiculoFabricanteId = "263", Nome = "MICRO-ONIBUS" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2225", VeiculoFabricanteId = "242", Nome = "113" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2255", VeiculoFabricanteId = "4", Nome = "1525" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2256", VeiculoFabricanteId = "4", Nome = "2621" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2297", VeiculoFabricanteId = "3", Nome = "210" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2354", VeiculoFabricanteId = "242", Nome = "110" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2355", VeiculoFabricanteId = "242", Nome = "LK-140" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2357", VeiculoFabricanteId = "242", Nome = "L-80" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2358", VeiculoFabricanteId = "242", Nome = "B-110" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2359", VeiculoFabricanteId = "242", Nome = "BR-115" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2362", VeiculoFabricanteId = "242", Nome = "B-111" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2363", VeiculoFabricanteId = "242", Nome = "BR-116" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2364", VeiculoFabricanteId = "242", Nome = "81" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2365", VeiculoFabricanteId = "242", Nome = "82" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2366", VeiculoFabricanteId = "242", Nome = "92" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2367", VeiculoFabricanteId = "242", Nome = "142" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2370", VeiculoFabricanteId = "242", Nome = "144" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2372", VeiculoFabricanteId = "242", Nome = "L-71" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2373", VeiculoFabricanteId = "242", Nome = "L-75" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2374", VeiculoFabricanteId = "242", Nome = "L-76" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2375", VeiculoFabricanteId = "242", Nome = "P-330" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2465", VeiculoFabricanteId = "13", Nome = "F-750" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2466", VeiculoFabricanteId = "4", Nome = "1625" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2478", VeiculoFabricanteId = "4", Nome = "2013" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2483", VeiculoFabricanteId = "4", Nome = "312" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2488", VeiculoFabricanteId = "85", Nome = "80S" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2490", VeiculoFabricanteId = "13", Nome = "F-6" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2497", VeiculoFabricanteId = "242", Nome = "490" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2504", VeiculoFabricanteId = "68", Nome = "180" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2506", VeiculoFabricanteId = "4", Nome = "1622" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2507", VeiculoFabricanteId = "4", Nome = "1524" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2512", VeiculoFabricanteId = "4", Nome = "1630" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2513", VeiculoFabricanteId = "4", Nome = "1932" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2531", VeiculoFabricanteId = "4", Nome = "1316" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2535", VeiculoFabricanteId = "242", Nome = "133" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2538", VeiculoFabricanteId = "1", Nome = "MATRA" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2539", VeiculoFabricanteId = "4", Nome = "1111" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2549", VeiculoFabricanteId = "1", Nome = "COE" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2550", VeiculoFabricanteId = "13", Nome = "COE" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2551", VeiculoFabricanteId = "3", Nome = "130" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2552", VeiculoFabricanteId = "13", Nome = "F-8" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2577", VeiculoFabricanteId = "2", Nome = "CONSTELLATION" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2578", VeiculoFabricanteId = "2", Nome = "DELIVERY" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2579", VeiculoFabricanteId = "2", Nome = "WORKER" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2601", VeiculoFabricanteId = "4", Nome = "321" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2602", VeiculoFabricanteId = "4", Nome = "1317" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2603", VeiculoFabricanteId = "3", Nome = "180" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2712", VeiculoFabricanteId = "266", Nome = "ESCAVADEIRA" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2713", VeiculoFabricanteId = "266", Nome = "MUNCK" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2714", VeiculoFabricanteId = "266", Nome = "GUINCHO" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2715", VeiculoFabricanteId = "266", Nome = "CARREGADEIRA" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2723", VeiculoFabricanteId = "266", Nome = "MOTONIVELADORA" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2724", VeiculoFabricanteId = "4", Nome = "2213" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2889", VeiculoFabricanteId = "266", Nome = "TANQUE" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2892", VeiculoFabricanteId = "266", Nome = "POLIGUINDASTE" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2893", VeiculoFabricanteId = "4", Nome = "1621" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2894", VeiculoFabricanteId = "13", Nome = "F-8000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2897", VeiculoFabricanteId = "274", Nome = "24250" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2898", VeiculoFabricanteId = "4", Nome = "1632" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2900", VeiculoFabricanteId = "266", Nome = "PERFURATRIZ" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2919", VeiculoFabricanteId = "4", Nome = "180" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2920", VeiculoFabricanteId = "4", Nome = "1517" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2929", VeiculoFabricanteId = "1", Nome = "C-65" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2930", VeiculoFabricanteId = "1", Nome = "D-11000" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2964", VeiculoFabricanteId = "1", Nome = "D-65" });
            Insert.IntoTable("VeiculoModelo").Row(new { VeiculoModeloId = "2971", VeiculoFabricanteId = "53", Nome = "FL SERIES" });
            Execute.Sql("SET IDENTITY_INSERT [dbo].[VeiculoModelo] OFF");
        }

        public override void Down()
        {
            throw new System.NotImplementedException();
        }
    }
}