SET IDENTITY_INSERT [dbo].[Estado] ON
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (1, N'Acre', N'AC', 12, N'68', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (2, N'Alagoas', N'AL', 27, N'82', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (3, N'Amazonas', N'AM', 13, N'97,92', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (4, N'Amapá', N'AP', 16, N'96', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (5, N'Bahia', N'BA', 29, N'77,75,73,74,71', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (6, N'Ceará', N'CE', 23, N'88,85', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (7, N'Distrito Federal', N'DF', 53, N'61', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (8, N'Espírito Santo', N'ES', 32, N'28,27', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (9, N'Goiás', N'GO', 52, N'62,64,61', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (10, N'Maranhão', N'MA', 21, N'99,98', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (11, N'Minas Gerais', N'MG', 31, N'34,37,31,33,35,38,32', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (12, N'Mato Grosso do Sul', N'MS', 50, N'67', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (13, N'Mato Grosso', N'MT', 51, N'65,66', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (14, N'Pará', N'PA', 15, N'91,94,93', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (15, N'Paraíba', N'PB', 25, N'83', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (16, N'Pernambuco', N'PE', 26, N'81,87', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (17, N'Piauí', N'PI', 22, N'89,86', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (18, N'Paraná', N'PR', 41, N'43,41,42,44,45,46', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (19, N'Rio de Janeiro', N'RJ', 33, N'24,22,21', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (20, N'Rio Grande do Norte', N'RN', 24, N'84', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (21, N'Rondônia', N'RO', 11, N'69', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (22, N'Roraima', N'RR', 14, N'95', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (23, N'Rio Grande do Sul', N'RS', 43, N'53,54,55,51', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (24, N'Santa Catarina', N'SC', 42, N'47,48,49', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (25, N'Sergipe', N'SE', 28, N'79', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (26, N'São Paulo', N'SP', 35, N'11,12,13,14,15,16,17,18,19', 1)
INSERT INTO dbo.Estado (EstadoId, Nome, UF, IBGE, DDD, PaisID) VALUES (27, N'Tocantins', N'TO', 17, N'63', 1)

SET IDENTITY_INSERT [dbo].[Estado] OFF