SET IDENTITY_INSERT [dbo].[Pais] ON 
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (1, N'Brasil' ,N'BR' ,N'Brazil',1058 ,N'brasileira')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (2, N'Afeganistão' ,N'AF' ,N'Afghanistan',132 ,N'afegãa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (3, N'Albânia, Republica da' ,N'AL' ,N'Albania',175 ,N'albanesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (4, N'Argélia' ,N'DZ' ,N'Algeria',590 ,N'argelina')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (5, N'Samoa Americana' ,N'AS' ,N'American Samoa',6912 ,N'samoense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (6, N'Andorra' ,N'AD' ,N'Andorra',370 ,N'andorrana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (7, N'Angola' ,N'AO' ,N'Angola',400 ,N'angolana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (8, N'Anguilla' ,N'AI' ,N'Anguilla',418 ,N'anguilana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (9, N'Antártida' ,N'AQ' ,N'Antarctica',3596 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (10, N'Antigua e Barbuda' ,N'AG' ,N'Antigua and Barbuda',434 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (11, N'Argentina' ,N'AR' ,N'Argentina',639 ,N'argentina')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (12, N'Armênia, Republica da' ,N'AM' ,N'Armenia',647 ,N'arménia')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (13, N'Aruba' ,N'AW' ,N'Aruba',655 ,N'arubana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (14, N'Austrália' ,N'AU' ,N'Australia',698 ,N'australiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (15, N'Áustria' ,N'AT' ,N'Austria',728 ,N'austríaca')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (16, N'Azerbaijão, Republica do' ,N'AZ' ,N'Azerbaijan',736 ,N'azeri')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (17, N'Bahamas, Ilhas' ,N'BS' ,N'Bahamas',779 ,N'baamiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (18, N'Bahrein, Ilhas' ,N'BH' ,N'Bahrain',809 ,N'barenita')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (19, N'Bangladesh' ,N'BD' ,N'Bangladesh',817 ,N'bangladechiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (20, N'Barbados' ,N'BB' ,N'Barbados',833 ,N'barbadense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (21, N'Belarus, Republica da' ,N'BY' ,N'Belarus',850 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (22, N'Bélgica' ,N'BE' ,N'Belgium',876 ,N'belga')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (23, N'Belize' ,N'BZ' ,N'Belize',884 ,N'belizenha')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (24, N'Benin' ,N'BJ' ,N'Benin',2291 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (25, N'Bermudas' ,N'BM' ,N'Bermuda',906 ,N'bermudense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (26, N'Butão' ,N'BT' ,N'Bhutan',1198 ,N'butanesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (27, N'Bolívia' ,N'BO' ,N'Bolivia',973 ,N'boliviana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (28, N'Bósnia-herzegovina (Republica da)' ,N'BA' ,N'Bosnia and Herzegowina',981 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (29, N'Botsuana' ,N'BW' ,N'Botswana',1015 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (30, N'Ilha Bouvet' ,N'BV' ,N'Bouvet Island',1023 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (31, N'Território Britânico do Oceano Indico' ,N'IO' ,N'British Indian Ocean Territory',7820 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (32, N'Brunei' ,N'BN' ,N'Brunei Darussalam',1082 ,N'bruneína')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (33, N'Bulgária, Republica da' ,N'BG' ,N'Bulgaria',1112 ,N'búlgara')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (34, N'Burkina Faso' ,N'BF' ,N'Burkina Faso',310 ,N'burquina')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (35, N'Burundi' ,N'BI' ,N'Burundi',1155 ,N'burundiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (36, N'Camboja' ,N'KH' ,N'Cambodia',1414 ,N'cambojana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (37, N'Camarões' ,N'CM' ,N'Cameroon',1457 ,N'camaronesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (38, N'Canada' ,N'CA' ,N'Canada',1490 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (39, N'Cabo Verde, Republica de' ,N'CV' ,N'Cape Verde',1279 ,N'cabo-verdiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (40, N'Cayman, Ilhas' ,N'KY' ,N'Cayman Islands',1376 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (41, N'Republica Centro-Africana' ,N'CF' ,N'Central African Republic',6408 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (42, N'Chade' ,N'TD' ,N'Chad',7889 ,N'chadiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (43, N'Chile' ,N'CL' ,N'Chile',1589 ,N'chilena')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (44, N'China, Republica Popular' ,N'CN' ,N'China',1600 ,N'china')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (45, N'Christmas, Ilha (Navidad)' ,N'CX' ,N'Christmas Island',5118 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (46, N'Cocos (Keeling) Ilhas' ,N'CC' ,N'Cocos (Keeling) Islands',1651 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (47, N'Colômbia' ,N'CO' ,N'Colombia',1694 ,N'colombiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (48, N'Comores, Ilhas' ,N'KM' ,N'Comoros',1732 ,N'comoriana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (49, N'Congo' ,N'CG' ,N'Congo',1775 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (50, N'Congo, Republica Democrática do' ,N'CD' ,N'Congo, the Democratic Republic of the',8885 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (51, N'Cook, Ilhas' ,N'CK' ,N'Cook Islands',1830 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (52, N'Costa Rica' ,N'CR' ,N'Costa Rica',1961 ,N'costarriquenha')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (53, N'Costa do Marfim' ,N'CI' ,N'Cote dIvoire',1937 ,N'marfinense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (54, N'Croácia (Republica da)' ,N'HR' ,N'Croatia (Hrvatska)',1953 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (55, N'Cuba' ,N'CU' ,N'Cuba',1996 ,N'cubana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (56, N'Chipre' ,N'CY' ,N'Cyprus',1635 ,N'cipriota')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (57, N'Tcheca, Republica' ,N'CZ' ,N'Czech Republic',7919 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (58, N'Dinamarca' ,N'DK' ,N'Denmark',2321 ,N'dinamarqua')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (59, N'Djibuti' ,N'DJ' ,N'Djibouti',7838 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (60, N'Dominica, Ilha' ,N'DM' ,N'Dominica',2356 ,N'dominiqua')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (61, N'Republica Dominicana' ,N'DO' ,N'Dominican Republic',6475 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (62, N'Timor Leste' ,N'TL' ,N'East Timor',7951 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (63, N'Equador' ,N'EC' ,N'Ecuador',2399 ,N'equatoriana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (64, N'Egito' ,N'EG' ,N'Egypt',2402 ,N'egípcia')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (65, N'El Salvador' ,N'SV' ,N'El Salvador',6874 ,N'salvadorenha')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (66, N'Guine-Equatorial' ,N'GQ' ,N'Equatorial Guinea',3310 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (67, N'Eritreia' ,N'ER' ,N'Eritrea',2437 ,N'eritreia')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (68, N'Estônia, Republica da' ,N'EE' ,N'Estonia',2518 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (69, N'Etiópia' ,N'ET' ,N'Ethiopia',2534 ,N'etíope')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (70, N'Falkland (Ilhas Malvinas)' ,N'FK' ,N'Falkland Islands (Malvinas)',2550 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (71, N'Feroe, Ilhas' ,N'FO' ,N'Faroe Islands',2593 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (72, N'Fiji' ,N'FJ' ,N'Fiji',8702 ,N'fijiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (73, N'Finlândia' ,N'FI' ,N'Finland',2712 ,N'finlandesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (74, N'Franca' ,N'FR' ,N'France',2755 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (76, N'Guiana francesa' ,N'GF' ,N'French Guiana',3255 ,N'guianense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (77, N'Polinésia Francesa' ,N'PF' ,N'French Polynesia',5991 ,N'polinésia')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (78, N'Terras Austrais e Antárticas Francesas' ,N'TF' ,N'French Southern Territories',3607 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (79, N'Gabão' ,N'GA' ,N'Gabon',2810 ,N'gabonesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (80, N'Gambia' ,N'GM' ,N'Gambia',2852 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (81, N'Georgia, Republica da' ,N'GE' ,N'Georgia',2917 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (82, N'Alemanha' ,N'DE' ,N'Germany',230 ,N'alemã')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (83, N'Gana' ,N'GH' ,N'Ghana',2895 ,N'ganesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (84, N'Gibraltar' ,N'GI' ,N'Gibraltar',2933 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (85, N'Grécia' ,N'GR' ,N'Greece',3018 ,N'grega')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (86, N'Groenlândia' ,N'GL' ,N'Greenland',3050 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (87, N'Granada' ,N'GD' ,N'Grenada',2976 ,N'granadina')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (88, N'Guadalupe' ,N'GP' ,N'Guadeloupe',3093 ,N'guadalupense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (89, N'Guam' ,N'GU' ,N'Guam',3131 ,N'guamesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (90, N'Guatemala' ,N'GT' ,N'Guatemala',3174 ,N'guatemalteca')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (91, N'Guine' ,N'GN' ,N'Guinea',3298 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (92, N'Guine-Bissau' ,N'GW' ,N'Guinea-Bissau',3344 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (93, N'Guiana' ,N'GY' ,N'Guyana',3379 ,N'guianesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (94, N'Haiti' ,N'HT' ,N'Haiti',3417 ,N'haitiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (95, N'Ilha Heard e Ilhas McDonald' ,N'HM' ,N'Heard and Mc Donald Islands',3603 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (96, N'Vaticano, Estado da Cidade do' ,N'VA' ,N'Holy See (Vatican City State)',8486 ,N'vaticana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (97, N'Honduras' ,N'HN' ,N'Honduras',3450 ,N'hondurenha')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (98, N'Hong Kong' ,N'HK' ,N'Hong Kong',3514 ,N'honconguesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (99, N'Hungria, Republica da' ,N'HU' ,N'Hungary',3557 ,N'húngara')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (100, N'Islândia' ,N'IS' ,N'Iceland',3794 ,N'islanda')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (101, N'Índia' ,N'IN' ,N'India',3611 ,N'indiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (102, N'Indonésia' ,N'ID' ,N'Indonesia',3654 ,N'indonésia')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (103, N'Ira, Republica Islâmica do' ,N'IR' ,N'Iran (Islamic Republic of)',3727 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (104, N'Iraque' ,N'IQ' ,N'Iraq',3697 ,N'iraquiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (105, N'Irlanda' ,N'IE' ,N'Ireland',3751 ,N'irlandesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (106, N'Israel' ,N'IL' ,N'Israel',3832 ,N'israelita')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (107, N'Itália' ,N'IT' ,N'Italy',3867 ,N'Italiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (108, N'Jamaica' ,N'JM' ,N'Jamaica',3913 ,N'jamaicana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (109, N'Japão' ,N'JP' ,N'Japan',3999 ,N'japonesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (110, N'Jordânia' ,N'JO' ,N'Jordan',4030 ,N'jordana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (111, N'Cazaquistão, Republica do' ,N'KZ' ,N'Kazakhstan',1538 ,N'cazaque')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (112, N'Quênia' ,N'KE' ,N'Kenya',6238 ,N'queniana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (113, N'Kiribati' ,N'KI' ,N'Kiribati',4111 ,N'quiribatiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (114, N'Coreia, Republica Popular Democrática da' ,N'KP' ,N'Korea, Democratic Peoples Republic of',1872 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (115, N'Coreia, Republica da' ,N'KR' ,N'Korea, Republic of',1902 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (116, N'Kuwait' ,N'KW' ,N'Kuwait',1988 ,N'kuwaitiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (117, N'Quirguiz, Republica' ,N'KG' ,N'Kyrgyzstan',6254 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (118, N'Laos, Republica Popular Democrática do' ,N'LA' ,N'Lao Peoples Democratic Republic',4200 ,N'laociana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (119, N'Letônia, Republica da' ,N'LV' ,N'Latvia',4278 ,N'letã')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (120, N'Líbano' ,N'LB' ,N'Lebanon',4316 ,N'libanesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (121, N'Lesoto' ,N'LS' ,N'Lesotho',4260 ,N'lesotiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (122, N'Libéria' ,N'LR' ,N'Liberia',4340 ,N'liberiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (123, N'Líbia' ,N'LY' ,N'Libyan Arab Jamahiriya',4383 ,N'líbia')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (124, N'Liechtenstein' ,N'LI' ,N'Liechtenstein',4405 ,N'listenstainiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (125, N'Lituânia, Republica da' ,N'LT' ,N'Lithuania',4421 ,N'lituana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (126, N'Luxemburgo' ,N'LU' ,N'Luxembourg',4456 ,N'luxemburguesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (127, N'Macau' ,N'MO' ,N'Macau',4472 ,N'macaense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (128, N'Macedônia, Antiga Republica Iugoslava' ,N'MK' ,N'Macedonia, The Former Yugoslav Republic of',4499 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (129, N'Madagascar' ,N'MG' ,N'Madagascar',4502 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (130, N'Malavi' ,N'MW' ,N'Malawi',4588 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (131, N'Malásia' ,N'MY' ,N'Malaysia',4553 ,N'malaia')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (132, N'Maldivas' ,N'MV' ,N'Maldives',4618 ,N'maldiva')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (133, N'Mali' ,N'ML' ,N'Mali',4642 ,N'maliano')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (134, N'Malta' ,N'MT' ,N'Malta',4677 ,N'maltesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (135, N'Marshall, Ilhas' ,N'MH' ,N'Marshall Islands',4766 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (136, N'Martinica' ,N'MQ' ,N'Martinique',4774 ,N'martinicana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (137, N'Mauritânia' ,N'MR' ,N'Mauritania',4880 ,N'mauritana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (138, N'Mauricio' ,N'MU' ,N'Mauritius',4855 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (139, N'Mayotte (Ilhas Francesas)' ,N'YT' ,N'Mayotte',4898 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (140, N'México' ,N'MX' ,N'Mexico',4936 ,N'mexicana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (141, N'Micronesia' ,N'FM' ,N'Micronesia, Federated States of',4995 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (142, N'Moldávia, Republica da' ,N'MD' ,N'Moldova, Republic of',4944 ,N'moldava')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (143, N'Mônaco' ,N'MC' ,N'Monaco',4952 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (144, N'Mongólia' ,N'MN' ,N'Mongolia',4979 ,N'mongol')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (145, N'Montserrat, Ilhas' ,N'MS' ,N'Montserrat',5010 ,N'monserratense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (146, N'Marrocos' ,N'MA' ,N'Morocco',4740 ,N'marroquina')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (147, N'Moçambique' ,N'MZ' ,N'Mozambique',5053 ,N'moçambicana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (148, N'Mianmar (Birmânia)' ,N'MM' ,N'Myanmar',930 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (149, N'Namíbia' ,N'NA' ,N'Namibia',5070 ,N'namibiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (150, N'Nauru' ,N'NR' ,N'Nauru',5088 ,N'nauruana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (151, N'Nepal' ,N'NP' ,N'Nepal',5177 ,N'nepalesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (152, N'Países Baixos (Holanda)' ,N'NL' ,N'Netherlands',5738 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (154, N'Nova Caledonia' ,N'NC' ,N'New Caledonia',5428 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (155, N'Nova Zelândia' ,N'NZ' ,N'New Zealand',5487 ,N'neozelandesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (156, N'Nicarágua' ,N'NI' ,N'Nicaragua',5215 ,N'nicaraguense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (157, N'Níger' ,N'NE' ,N'Niger',5258 ,N'nigerina')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (158, N'Nigéria' ,N'NG' ,N'Nigeria',5282 ,N'nigeriana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (159, N'Niue, Ilha' ,N'NU' ,N'Niue',5312 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (160, N'Norfolk, Ilha' ,N'NF' ,N'Norfolk Island',5355 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (161, N'Marianas do Norte' ,N'MP' ,N'Northern Mariana Islands',4723 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (162, N'Noruega' ,N'NO' ,N'Norway',5380 ,N'norueguesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (163, N'Oma' ,N'OM' ,N'Oman',5568 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (164, N'Paquistão' ,N'PK' ,N'Pakistan',5762 ,N'paquistanesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (165, N'Palau' ,N'PW' ,N'Palau',5754 ,N'palauana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (166, N'Panamá' ,N'PA' ,N'Panama',5800 ,N'panamenha')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (167, N'Papua Nova Guine' ,N'PG' ,N'Papua New Guinea',5452 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (168, N'Paraguai' ,N'PY' ,N'Paraguay',5860 ,N'paraguaia')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (169, N'Peru' ,N'PE' ,N'Peru',5894 ,N'peruana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (170, N'Filipinas' ,N'PH' ,N'Philippines',2674 ,N'filipino')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (171, N'Pitcairn, Ilha' ,N'PN' ,N'Pitcairn',5932 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (172, N'Polônia, Republica da' ,N'PL' ,N'Poland',6033 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (173, N'Portugal' ,N'PT' ,N'Portugal',6076 ,N'portuguesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (174, N'Porto Rico' ,N'PR' ,N'Puerto Rico',6114 ,N'porto-riquenha')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (175, N'Catar' ,N'QA' ,N'Qatar',1546 ,N'catariana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (176, N'Reunião, Ilha' ,N'RE' ,N'Reunion',6602 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (177, N'Romênia' ,N'RO' ,N'Romania',6700 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (178, N'Rússia, Federação da' ,N'RU' ,N'Russian Federation',6769 ,N'russa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (179, N'Ruanda' ,N'RW' ,N'Rwanda',6750 ,N'ruandesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (180, N'São Cristovão e Neves, Ilhas' ,N'KN' ,N'Saint Kitts and Nevis',6955 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (181, N'Santa Lucia' ,N'LC' ,N'Saint LUCIA',7153 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (182, N'São Vicente e Granadinas' ,N'VC' ,N'Saint Vincent and the Grenadines',7056 ,N'são-vicentina')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (183, N'Samoa' ,N'WS' ,N'Samoa',6904 ,N'samoana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (184, N'San Marino' ,N'SM' ,N'San Marino',6971 ,N'são-marinhense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (185, N'São Tome e Príncipe, Ilhas' ,N'ST' ,N'Sao Tome and Principe',7200 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (186, N'Arábia Saudita' ,N'SA' ,N'Saudi Arabia',531 ,N'árabe-saudita')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (187, N'Senegal' ,N'SN' ,N'Senegal',7285 ,N'senegalesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (188, N'Seychelles' ,N'SC' ,N'Seychelles',7315 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (189, N'Serra Leoa' ,N'SL' ,N'Sierra Leone',7358 ,N'serra-leonesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (190, N'Cingapura' ,N'SG' ,N'Singapore',7412 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (191, N'Eslovaca, Republica' ,N'SK' ,N'Slovakia (Slovak Republic)',2470 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (192, N'Eslovênia, Republica da' ,N'SI' ,N'Slovenia',2461 ,N'eslovena')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (193, N'Salomão, Ilhas' ,N'SB' ,N'Solomon Islands',6777 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (194, N'Somalia' ,N'SO' ,N'Somalia',7480 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (195, N'África do Sul' ,N'ZA' ,N'South Africa',7560 ,N'sul-africana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (196, N'Ilhas Geórgia do Sul e Sandwich do Sul' ,N'GS' ,N'South Georgia and the South Sandwich Islands',2925 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (197, N'Espanha' ,N'ES' ,N'Spain',2453 ,N'espanhola')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (198, N'Sri Lanka' ,N'LK' ,N'Sri Lanka',7501 ,N'cingalesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (199, N'Santa Helena' ,N'SH' ,N'St. Helena',7102 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (200, N'São Pedro e Miquelon' ,N'PM' ,N'St. Pierre and Miquelon',7005 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (201, N'Sudão' ,N'SD' ,N'Sudan',7595 ,N'sudanesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (202, N'Suriname' ,N'SR' ,N'Suriname',7706 ,N'surinamesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (203, N'Svalbard e Jan Mayen' ,N'SJ' ,N'Svalbard and Jan Mayen Islands',7552 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (204, N'Suazilândia' ,N'SZ' ,N'Swaziland',7544 ,N'suazilandêa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (205, N'Suécia' ,N'SE' ,N'Sweden',7641 ,N'sueca')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (206, N'Suíça' ,N'CH' ,N'Switzerland',7676 ,N'suíça')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (207, N'Síria, Republica Árabe da' ,N'SY' ,N'Syrian Arab Republic',7447 ,N'síria')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (208, N'Formosa (Taiwan)' ,N'TW' ,N'Taiwan, Province of China',1619 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (209, N'Tadjiquistao, Republica do' ,N'TJ' ,N'Tajikistan',7722 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (210, N'Tanzânia, Republica Unida da' ,N'TZ' ,N'Tanzania, United Republic of',7803 ,N'tanzaniana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (211, N'Tailândia' ,N'TH' ,N'Thailand',7765 ,N'tailandês')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (212, N'Togo' ,N'TG' ,N'Togo',8001 ,N'togolesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (213, N'Toquelau, Ilhas' ,N'TK' ,N'Tokelau',8052 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (214, N'Tonga' ,N'TO' ,N'Tonga',8109 ,N'tonganesa')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (215, N'Trinidad e Tobago' ,N'TT' ,N'Trinidad and Tobago',8150 ,N'trinitária-tobagense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (216, N'Tunísia' ,N'TN' ,N'Tunisia',8206 ,N'tunisina')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (217, N'Turquia' ,N'TR' ,N'Turkey',8273 ,N'turca')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (218, N'Turcomenistão, Republica do' ,N'TM' ,N'Turkmenistan',8249 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (219, N'Turcas e Caicos, Ilhas' ,N'TC' ,N'Turks and Caicos Islands',8230 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (220, N'Tuvalu' ,N'TV' ,N'Tuvalu',8281 ,N'tuvaluana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (221, N'Uganda' ,N'UG' ,N'Uganda',8338 ,N'ugandense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (222, N'Ucrânia' ,N'UA' ,N'Ukraine',8311 ,N'ucraniana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (223, N'Emirados Árabes Unidos' ,N'AE' ,N'United Arab Emirates',2445 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (224, N'Reino Unido' ,N'GB' ,N'United Kingdom',6289 ,N'britânica')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (225, N'Estados Unidos' ,N'US' ,N'United States',2496 ,N'norte-americana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (226, N'Ilhas Menores Distantes dos Estados Unidos' ,N'UM' ,N'United States Minor Outlying Islands',18664 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (227, N'Uruguai' ,N'UY' ,N'Uruguay',8451 ,N'uruguaia')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (228, N'Uzbequistão, Republica do' ,N'UZ' ,N'Uzbekistan',8478 ,N'usbeque')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (229, N'Vanuatu' ,N'VU' ,N'Vanuatu',5517 ,N'vanuatuense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (230, N'Venezuela' ,N'VE' ,N'Venezuela',8508 ,N'venezuelana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (231, N'Vietnã' ,N'VN' ,N'Viet Nam',8583 ,N'vietnamita')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (232, N'Virgens, Ilhas (Britânicas)' ,N'VG' ,N'Virgin Islands (British)',8630 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (233, N'Virgens, Ilhas (E.U.A.)' ,N'VI' ,N'Virgin Islands (U.S.)',8664 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (234, N'Wallis e Futuna, Ilhas' ,N'WF' ,N'Wallis and Futuna Islands',8753 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (235, N'Saara Ocidental' ,N'EH' ,N'Western Sahara',6858 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (236, N'Iémen' ,N'YE' ,N'Yemen',3573 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (237, N'Iugoslávia, República Fed. da' ,N'YU' ,N'Yugoslavia',3883 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (238, N'Zâmbia' ,N'ZM' ,N'Zambia',8907 ,N'zambiana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (239, N'Zimbabue' ,N'ZW' ,N'Zimbabwe',6653 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (240, N'Guernsey, Ilha do Canal (Inclui Alderney e Sark)' ,N'GG' ,N'Bailiwick of Guernsey',3212 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (241, N'Jersey, Ilha do Canal' ,N'JE' ,N'Bailiwick of Jersey',3930 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (243, N'Man, Ilha de' ,N'IM' ,N'Isle of Man',3595 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (246, N'Montenegro' ,N'ME' ,N'Crna Gora (Montenegro)',4985 ,N'montenegrina')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (247, N'Republika Srbija' ,N'RS' ,N'SÉRVIA',7370 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (248, N'Sudao do Sul' ,N'SS' ,N'Republic of South Sudan',7600 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (249, N'Zona do Canal do Panamá' ,N'ZCP' ,N'Zona del Canal de Panamá',8958 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (252, N'Palestina' ,N'PS' ,N'Dawlat Filas?in',5780 ,N'palestiniana')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (253, N'Ilhas de Aland' ,N'AX' ,N'Åland Islands',153 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (255, N'Curaçao' ,N'CW' ,N'Curaçao',2003 ,N'curaçauense')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (256, N'Ilha de São Martinho (Países Baixos)' ,N'SM' ,N'Saint Martin',6998 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (258, N'Bonaire' ,N'AN' ,N'Bonaire',990 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (259, N'Antartica' ,N'AQ' ,N'Antartica',420 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (260, N'Ilha Herad e Ilhas Macdonald' ,N'AU' ,N'Heard Island and McDonald Islands',3433 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (261, N'Colectividade de São Bartolomeu' ,N'FR' ,N'Collectivité de Saint-Barthélemy',6939 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (262, N'Ilha de São Martinho (França)' ,N'SM' ,N'Saint Martin',6980 ,N'')
INSERT INTO dbo.Pais (PaisId, Nome ,Sigla ,NomeInternacional ,BACEN ,Nacionalidade) VALUES (263, N'Território das Terras Austrais e Antárcticas Francesas' ,N'TF' ,N'Territoire des Terres australes et antarctiques françaises',7811 ,N'')
SET IDENTITY_INSERT [dbo].[Pais] OFF